#!/bin/bash
# Demo script for Linux Virtual Sound Card
# This script demonstrates the sine wave generator and verification test

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Linux Virtual Sound Card Demo${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Check if programs exist
if [ ! -f "build/sine_generator_app" ]; then
    echo -e "${RED}Error: Programs not built. Run 'make' first.${NC}"
    exit 1
fi

# Check if snd-aloop is loaded
if ! lsmod | grep -q snd_aloop; then
    echo -e "${YELLOW}Warning: snd-aloop module not loaded${NC}"
    echo "Attempting to load module..."
    if sudo modprobe snd-aloop 2>/dev/null; then
        echo -e "${GREEN}Module loaded successfully${NC}"
    else
        echo -e "${RED}Error: Could not load snd-aloop module${NC}"
        echo "You may need to:"
        echo "  1. Install kernel modules: sudo apt-get install linux-modules-extra-\$(uname -r)"
        echo "  2. Or rebuild kernel with CONFIG_SND_ALOOP=m"
        exit 1
    fi
else
    echo -e "${GREEN}snd-aloop module is loaded${NC}"
fi
echo ""

# Verify loopback devices
echo "Checking for loopback devices..."
if aplay -l | grep -q Loopback; then
    echo -e "${GREEN}Loopback devices found:${NC}"
    aplay -l | grep -A 1 Loopback
else
    echo -e "${RED}Error: No loopback devices found${NC}"
    exit 1
fi
echo ""

# Demo parameters
FREQUENCY=440
DURATION=5

echo -e "${BLUE}Demo Configuration:${NC}"
echo "  Frequency: ${FREQUENCY} Hz (A4 note)"
echo "  Duration: ${DURATION} seconds"
echo ""

echo -e "${YELLOW}Starting sine wave generator in background...${NC}"
./build/sine_generator_app ${FREQUENCY} ${DURATION} > /tmp/sine_gen_demo.log 2>&1 &
SINE_PID=$!

# Give it a moment to start
sleep 1

# Check if it's still running
if ! kill -0 $SINE_PID 2>/dev/null; then
    echo -e "${RED}Error: Sine generator failed to start${NC}"
    cat /tmp/sine_gen_demo.log
    exit 1
fi

echo -e "${GREEN}Sine generator started (PID: ${SINE_PID})${NC}"
echo ""

# Wait a bit for audio to start
sleep 0.5

echo -e "${YELLOW}Running verification test...${NC}"
echo ""
if ./build/test_loopback_read; then
    TEST_RESULT=0
else
    TEST_RESULT=$?
fi

echo ""

# Clean up
if kill -0 $SINE_PID 2>/dev/null; then
    kill $SINE_PID 2>/dev/null || true
    wait $SINE_PID 2>/dev/null || true
fi

# Show results
echo -e "${BLUE}========================================${NC}"
if [ $TEST_RESULT -eq 0 ]; then
    echo -e "${GREEN}✓ Demo completed successfully!${NC}"
    echo ""
    echo "The virtual sound card is working correctly."
    echo "Audio was successfully:"
    echo "  1. Generated by sine_generator_app"
    echo "  2. Transmitted through the loopback device"
    echo "  3. Received and verified by test_loopback_read"
else
    echo -e "${RED}✗ Demo failed${NC}"
    echo ""
    echo "The verification test did not pass."
    echo "Check the output above for details."
fi
echo -e "${BLUE}========================================${NC}"

exit $TEST_RESULT
